#!/bin/sh
set -eu

CONFIG_DIR="$HOME/.ai-coding"
CONFIG_FILE="$CONFIG_DIR/providers.env"

mkdir -p "$CONFIG_DIR"

echo "AI Provider Setup Wizard"
echo "------------------------"
echo "This wizard stores API tokens locally in: $CONFIG_FILE"
echo "Leave a value blank to skip that provider."
echo

printf "Enter OpenAI API token (for GPT-5.3 Codex): "
stty -echo
read -r OPENAI_API_KEY
stty echo
printf "\n"

printf "Enter Anthropic API token (for Claude Opus 4.6): "
stty -echo
read -r ANTHROPIC_API_KEY
stty echo
printf "\n"

DEFAULT_PROVIDER=""
if [ -n "$OPENAI_API_KEY" ] && [ -n "$ANTHROPIC_API_KEY" ]; then
  DEFAULT_PROVIDER="codex"
elif [ -n "$OPENAI_API_KEY" ]; then
  DEFAULT_PROVIDER="codex"
elif [ -n "$ANTHROPIC_API_KEY" ]; then
  DEFAULT_PROVIDER="opus"
fi

umask 077
{
  echo "# Generated by setup_ai_tokens_in_macos.sh"
  echo "OPENAI_API_KEY=$OPENAI_API_KEY"
  echo "ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY"
  echo "DEFAULT_PROVIDER=$DEFAULT_PROVIDER"
} > "$CONFIG_FILE"

if [ -n "$DEFAULT_PROVIDER" ]; then
  echo "Saved provider config. Default provider: $DEFAULT_PROVIDER"
else
  echo "No tokens provided. Config file created but no default provider set."
fi

echo "You can load tokens in shell with:"
echo "  set -a; . $CONFIG_FILE; set +a"
